apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  namespace: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80