apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-hackathon-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-hackathon-repo