apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-hackathon-kustomization
spec:
  interval: 1m
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-hackathon-repo