apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-deployment
  namespace: hackathon-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon
  template:
    metadata:
      labels:
        app: hackathon
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
