name: Build and Push Docker Images

on:
  push:
    branches:
      - production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and Push PHP Image
        uses: docker/build-push-action@v2
        with:
          context: ./php/
          push: true
          tags: ghcr.io/robinvandijk/flux-hackathon/php:latest
      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v2
        with:
          context: ./nginx/
          push: true
          tags: ghcr.io/robinvandijk/flux-hackathon/nginx:latest