name: Create Review Environment
on:
  push:
    branches:
      - '**' # Trigger on all branch pushes except main

jobs:
  create-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Branch Name
        id: set-branch-name
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create Namespace and Deployment Manifests
        run: |
          BRANCH_NAME=${{ env.BRANCH_NAME }}
          FEATURE_BRANCH_DIR="templates/feature-branch"
          OUTPUT_DIR="clusters/minikube/environments/$BRANCH_NAME"

          # Create output directory
          mkdir -p $OUTPUT_DIR

          # Replace placeholders in templates and create files
          for template_file in $FEATURE_BRANCH_DIR/*.yaml; do
            output_file="$OUTPUT_DIR/$(basename $template_file)"
            sed -e "s#{{branch-name}}#$BRANCH_NAME#g" $template_file > $output_file
          done

      - name: Fetch All Branches
        run: git fetch --all

      - name: Configure Git for Authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://github.com/RobinVanDijk/flux-hackathon.git
          git config credential.helper 'store --file=.git-credentials'
          echo "https://$GITHUB_TOKEN:x-oauth-basic" > .git-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Checkout Production Branch
        run: git checkout production || git checkout -b production

      - name: Commit and Push Changes
        run: |
          git add environments/$BRANCH_NAME
          git commit -m "Add environment for branch $BRANCH_NAME"
          git push origin production
          
      
